site_name: REV Opacity Cutout
site_url: https://revolutionart.github.io/REVOpacityCutout.github.io/
repo_url: https://github.com/revolutionart/REVOpacityCutout.github.io
repo_name: revolutionart/REVOpacityCutout.github.io
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Getting Started:
      - Introduction: getting-started/introduction.md
      - Learning Videos: getting-started/learning-videos.md
      - Installation and Update: getting-started/installation-and-update.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
